const server = [
    {
        id: 1,
        title: '1111',
        data: '4 day ago',
        dataInMin: 4*24*60,
        autor: 'Danila',
        autorId: 11111,
        points: 10,
        like: false,
    },
    {
        id: 2,
        title: '2222',
        data: '1 day ago',
        dataInMin: 1*24*60,
        autor: 'Maxim',
        autorId: 222222,
        points: 15,
        like: false,
    },
    {
        id: 3,
        title: '3333',
        data: '6 day ago',
        dataInMin: 6*24*60,
        autor: 'Ladys',
        autorId: 333333,
        points: 5,
        like: false,
    },
    {
        id: 4,
        title: '4444',
        data: '6 day ago',
        dataInMin: 6*24*60,
        autor: 'mali',
        autorId: 44444,
        points: 25,
        like: false,
    },
    {
        id: 5,
        title: '5555',
        data: '9 day ago',
        dataInMin: 9*24*60,
        autor: 'leut',
        autorId: 555,
        points: 10,
        like: false,
    },
    {
        id: 6,
        title: '6666',
        data: '2 day ago',
        dataInMin: 2*24*60,
        autor: 'geyme',
        autorId: 555,
        points: 15,
        like: false,
    },
    {
        id: 7,
        title: '7777',
        data: '7 day ago',
        dataInMin: 7*24*60,
        autor: 'blue',
        autorId: 555,
        points: 5,
        like: true,
    },
    {
        id: 8,
        title: '8888',
        data: '4 day ago',
        dataInMin: 4*24*60,
        autor: 'red',
        autorId: 5555,
        points: 25,
        like: false,
    },
    {
        id: 9,
        title: '8b88b8t',
        data: '4 day ago',
        dataInMin: 4*24*60,
        autor: 'red',
        autorId: 999,
        points: 12,
        like: false,
    },
];

export default server